export default {
  name: 'trip',
  title: 'Trip',
  type: 'document',
  fields: [
    { name: 'name', title: 'Trip Name', type: 'string' },
    { name: 'slug', title: 'Slug (URL-safe id, e.g., "thunder-dragon")', type: 'slug', options: { source: 'name' } },
    { name: 'loc', title: 'Location', type: 'string', description: 'e.g., Bhutan · S. Asia' },
    { name: 'region', title: 'Region', type: 'string', options: { list: ['India', 'International'] } },
    { name: 'route', title: 'Route', type: 'string', description: 'e.g., Paro → Thimphu → Punakha' },
    { name: 'duration', title: 'Duration', type: 'string', description: 'e.g., 7D / 6N' },
    { name: 'pickup', title: 'Pickup Location', type: 'string' },
    { name: 'departureDate', title: 'Departure Date', type: 'string' },
    { name: 'price', title: 'Full Price (₹)', type: 'number' },
    { name: 'advance', title: 'Advance Booking Amount (₹)', type: 'number' },
    { name: 'originalPrice', title: 'Original Price (₹) — shown crossed out', type: 'number' },
    { name: 'seatsLeft', title: 'Seats Left', type: 'number' },
    { name: 'totalSeats', title: 'Total Seats', type: 'number' },
    { name: 'tag', title: 'Tag', type: 'string', description: 'e.g., Workation, Coliving, Skill Share' },
    { name: 'tagColor', title: 'Tag Color (hex)', type: 'string', description: 'e.g., #D44424' },
    { name: 'img', title: 'Card Image', type: 'image', options: { hotspot: true } },
    { name: 'heroImg', title: 'Hero Image (large)', type: 'image', options: { hotspot: true } },
    { name: 'pitch', title: 'One-line Pitch', type: 'text', rows: 2 },
    { name: 'overview', title: 'Overview', type: 'text', rows: 6 },
    { name: 'highlights', title: 'Highlights', type: 'array', of: [{ type: 'string' }] },
    {
      name: 'itinerary', title: 'Day-by-Day Itinerary', type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'day', title: 'Day Number', type: 'number' },
          { name: 'title', title: 'Day Title', type: 'string' },
          { name: 'dist', title: 'Distance / Duration (optional)', type: 'string' },
          { name: 'desc', title: 'Activities', type: 'array', of: [{ type: 'string' }] },
        ],
      }],
    },
    { name: 'inclusions', title: 'Inclusions', type: 'array', of: [{ type: 'string' }] },
    { name: 'exclusions', title: 'Exclusions', type: 'array', of: [{ type: 'string' }] },
    { name: 'order', title: 'Display Order', type: 'number', description: 'Lower numbers appear first' },
  ],
  orderings: [{ title: 'Display Order', name: 'orderAsc', by: [{ field: 'order', direction: 'asc' }] }],
};
